name: Merge automated pull requests

on:
  pull_request:
    types:
      - labeled

jobs:
  merge-pr:
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check if they are an repository owner
        id: ownership
        run: |
          OWNER="${{ github.repository_owner }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          OK=false
          if [[ $OWNER == $AUTHOR ]]; then
            OK=true
          fi
          echo value="$OK" >> $GITHUB_OUTPUT
      - if: ${{ steps.ownership.outputs.value == 'true' }}
        uses: actions/checkout@v3
      - if: ${{ steps.ownership.outputs.value == 'true' }}
        name: Merge eligible PR
        # --delete-branch will cause error because
        # it was fixed in [2.29.0](https://github.com/cli/cli/commit/39bd9aafdcfe60cfdc3b78ef98f315f5f898e918)
        # but the runner has [2.28.0](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md?plain=1#L118)
        # using checkout action might fix it, but there's "Automatically delete head branches" in repo settings
        run: gh pr merge $PR_NUMBER --auto --merge
