name: Merge automated pull requests

on:
  pull_request:
    types:
      - labeled

jobs:
  merge-pr:
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check if they are an repository owner
        id: ownership
        run: |
          OWNER="${{ github.repository_owner }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          OK=false
          if [[ $OWNER == $AUTHOR ]]; then
            OK=true
          fi
          echo value=OK >> $GITHUB_OUTPUT
      - if: ${{ steps.ownership.outputs.value == 'true' }}
        name: Merge eligible PR
        run: gh pr merge $PR_NUMBER --auto --delete-branch
      

